services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: booking-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@Passw0rd123" # یک پسورد قوی
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build: .
    container_name: my-booking-api
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=BookingDb;User Id=sa;Password=YourStrong@Passw0rd123;TrustServerCertificate=True
    ports:
      - "5050:8080"

volumes:
  sql_data:
